spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/api-tuning
    username: dongha
    password: dongha
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  flyway:
    enabled: true
    baseline-on-migrate: true
    validate-on-migrate: true
    out-of-order: false