spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bench_idx_on?reWriteBatchedInserts=true
    username: dongha
    password: dongha
  flyway:
    enabled: true
    clean-disabled: false
server:
  port: 8080
