groups:
  - name: http-latency
    rules:
      - record: http:p95
        expr: histogram_quantile(0.95, sum(rate(http_server_requests_seconds_bucket[1m])) by (le,application,scenario,uri,method,status))
      - record: http:p99
        expr: histogram_quantile(0.99, sum(rate(http_server_requests_seconds_bucket[5m])) by (le,application,scenario,uri,method,status))
