-- 1) 상품
CREATE TABLE IF NOT EXISTS product
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       VARCHAR(200)   NOT NULL,
    price      NUMERIC(12, 2) NOT NULL CHECK (price >= 0),
    currency   CHAR(3)        NOT NULL DEFAULT 'USD' CHECK (char_length(currency) = 3 AND currency = upper(currency)),
    status     VARCHAR(20)    NOT NULL CHECK (status IN ('ACTIVE', 'INACTIVE')),
    created_at TIMESTAMPTZ    NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ    NOT NULL DEFAULT now()
);


-- 2) 주문
CREATE TABLE IF NOT EXISTS orders
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id      BIGINT         NOT NULL,
    status       VARCHAR(20)    NOT NULL CHECK (status IN ('PENDING', 'PAID', 'CANCELLED')),
    total_amount NUMERIC(12, 2) NOT NULL CHECK (total_amount >= 0),
    created_at   TIMESTAMPTZ    NOT NULL DEFAULT now(),
    updated_at   TIMESTAMPTZ    NOT NULL DEFAULT now()
);

-- 3) 주문 아이템
CREATE TABLE IF NOT EXISTS order_item
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id   BIGINT         NOT NULL REFERENCES orders (id) ON DELETE CASCADE,
    product_id BIGINT         NOT NULL REFERENCES product (id),
    unit_price NUMERIC(12, 2) NOT NULL CHECK (unit_price >= 0),
    quantity   INT            NOT NULL CHECK (quantity > 0),
    created_at TIMESTAMPTZ    NOT NULL DEFAULT now()
);

-- 4) 재고
CREATE TABLE IF NOT EXISTS inventory
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id  BIGINT NOT NULL UNIQUE REFERENCES product(id),
    quantity    INT NOT NULL CHECK (quantity >= 0),
    updated_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- 5) 재고 변경 로그
CREATE TABLE IF NOT EXISTS inventory_log
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id  BIGINT NOT NULL REFERENCES product(id),
    change_qty  INT NOT NULL,
    reason      VARCHAR(100) NOT NULL,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- 6) 멱등 키 저장
CREATE TABLE IF NOT EXISTS idempotency_key
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    key           VARCHAR(64) NOT NULL,
    response_body TEXT,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uk_idempotency_key UNIQUE (key)
);


COMMENT ON TABLE  idempotency_key IS 'Idempotency 키 저장소 (중복 요청 방지 및 응답 캐싱)';
COMMENT ON COLUMN idempotency_key.key IS 'Idempotency Key 값';
COMMENT ON COLUMN idempotency_key.response_body IS '이전에 반환된 응답 JSON';
COMMENT ON COLUMN idempotency_key.created_at IS '생성 시각';